a = input("player one, type your input for rock, with a r, paper, with p, or scissors, with s: ")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("the program has input a bunch of empty lines so as to make player one's answer unreadable")
print("without scrolling. Player two, please don't cheat.")
b = input("player two, type your selection here: ")
if a == 'r' and b == 's':
    print("player one wins!")
elif a == 'r' and b == 'p':
    print("player two wins!")
elif a == 'p' and b == 'r':
    print("player one wins!")
elif a == 'p' and b == 's':
    print("player two wins!")
elif a == 's' and b == 'r':
    print("player two wins!")
elif a == 's' and b == 'p':
    print("player one wins!")
elif a == b:
    print("you all lose!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! you chose the same option!!!!!!!!!!!!!")
else:
    print("one of you chose something that wasn't an option. Good job!")
